# Generated by Django 5.2.7 on 2026-01-31 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#6b7280",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarketingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("brochure", "Brochure"),
                            ("case_study", "Case Study"),
                            ("pricing", "Pricing Sheet"),
                            ("proposal", "Proposal Template"),
                            ("presentation", "Presentation"),
                            ("one_pager", "One-Pager"),
                            ("faq", "FAQ"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="acquisitions/documents/"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="External URL (if not uploaded)"
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "is_internal_only",
                    models.BooleanField(
                        default=False, help_text="Only visible to internal sellers"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketing Document",
                "verbose_name_plural": "Marketing Documents",
                "ordering": ["document_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="OutreachCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "max_contacts_per_day",
                    models.PositiveIntegerField(
                        default=50, help_text="Maximum outreach attempts per day"
                    ),
                ),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Outreach Campaign",
                "verbose_name_plural": "Outreach Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="User ID from get_user_model()",
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "email_signature",
                    models.TextField(
                        blank=True, help_text="HTML signature for outreach emails"
                    ),
                ),
                (
                    "auto_assign_prospective_clients",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically assign new prospective clients to this seller",
                    ),
                ),
                (
                    "max_active_prospective_clients",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum prospective clients in active pipeline",
                    ),
                ),
                ("working_hours_start", models.TimeField(default="09:00")),
                ("working_hours_end", models.TimeField(default="17:00")),
                (
                    "working_days",
                    models.CharField(
                        default="1,2,3,4,5",
                        help_text="Comma-separated days (1=Mon, 7=Sun)",
                        max_length=20,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/New_York", max_length=50),
                ),
                ("total_converted", models.PositiveIntegerField(default=0)),
                (
                    "active_prospective_clients_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Seller Profile",
                "verbose_name_plural": "Seller Profiles",
            },
        ),
        migrations.CreateModel(
            name="ProspectiveClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("proposal", "Proposal Sent"),
                            ("negotiation", "Negotiation"),
                            ("won", "Won (Converted)"),
                            ("lost", "Lost"),
                            ("dormant", "Dormant"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("referral", "Referral"),
                            ("website", "Website"),
                            ("cold_call", "Cold Call"),
                            ("trade_show", "Trade Show"),
                            ("social", "Social Media"),
                            ("ad", "Advertisement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, help_text="Score (higher = more qualified)"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5, help_text="Priority 1-10 (1 = highest priority)"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated annual contract value",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of assigned seller",
                        null=True,
                    ),
                ),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "converted_to_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the account/customer after conversion",
                        null=True,
                    ),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="Sample prospective client created during setup",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="prospective_clients",
                        to="acquisitions.category",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospective_clients",
                        to="acquisitions.industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospective Client",
                "verbose_name_plural": "Prospective Clients",
                "ordering": ["priority", "-score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                ("next_step_scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="acquisitions.outreachcampaign",
                    ),
                ),
                (
                    "prospective_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_enrollments",
                        to="acquisitions.prospectiveclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Enrollment",
                "verbose_name_plural": "Campaign Enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="ProspectiveClientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("decision_maker", "Decision Maker"),
                            ("influencer", "Influencer"),
                            ("champion", "Champion"),
                            ("end_user", "End User"),
                            ("gatekeeper", "Gatekeeper"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("phone_mobile", models.CharField(blank=True, max_length=20)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("sms", "SMS"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("best_time_to_contact", models.CharField(blank=True, max_length=100)),
                ("opted_out_email", models.BooleanField(default=False)),
                ("opted_out_sms", models.BooleanField(default=False)),
                ("opted_out_phone", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prospective_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="acquisitions.prospectiveclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospective Client Contact",
                "verbose_name_plural": "Prospective Client Contacts",
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Touchpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "touchpoint_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone Call"),
                            ("sms", "SMS/Text"),
                            ("meeting", "Meeting"),
                            ("video", "Video Call"),
                            ("social", "Social Media"),
                            ("mail", "Physical Mail"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("outbound", "Outbound (We contacted them)"),
                            ("inbound", "Inbound (They contacted us)"),
                        ],
                        default="outbound",
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Successful"),
                            ("no_answer", "No Answer"),
                            ("voicemail", "Left Voicemail"),
                            ("bounced", "Email Bounced"),
                            ("declined", "Declined/Not Interested"),
                            ("follow_up", "Requires Follow-up"),
                            ("pending", "Pending Response"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of call/meeting in minutes",
                        null=True,
                    ),
                ),
                (
                    "performed_by_id",
                    models.IntegerField(
                        blank=True,
                        help_text="User ID who performed this touchpoint",
                        null=True,
                    ),
                ),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="Was this touchpoint automated (vs manual)?",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External message ID (Twilio SID, email message-id, etc.)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="touchpoints",
                        to="acquisitions.outreachcampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific contact person if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="touchpoints",
                        to="acquisitions.prospectiveclientcontact",
                    ),
                ),
                (
                    "prospective_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="touchpoints",
                        to="acquisitions.prospectiveclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Touchpoint",
                "verbose_name_plural": "Touchpoints",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.PositiveIntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("email", "Send Email"),
                            ("sms", "Send SMS"),
                            ("task", "Create Task (Manual)"),
                            ("wait", "Wait Period"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delay_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Days to wait after previous step"
                    ),
                ),
                (
                    "delay_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Additional hours to wait"
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=255)),
                ("body_template", models.TextField(blank=True)),
                (
                    "skip_if_responded",
                    models.BooleanField(
                        default=True, help_text="Skip this step if lead has responded"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="acquisitions.outreachcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Step",
                "verbose_name_plural": "Campaign Steps",
                "ordering": ["step_order"],
                "unique_together": {("campaign", "step_order")},
            },
        ),
        migrations.AddIndex(
            model_name="prospectiveclient",
            index=models.Index(
                fields=["status", "priority"], name="acquisition_status_06506c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospectiveclient",
            index=models.Index(
                fields=["assigned_to_id", "status"],
                name="acquisition_assigne_57f34c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignenrollment",
            unique_together={("prospective_client", "campaign")},
        ),
        migrations.AddIndex(
            model_name="touchpoint",
            index=models.Index(
                fields=["touchpoint_type", "occurred_at"],
                name="acquisition_touchpo_d8832d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touchpoint",
            index=models.Index(
                fields=["prospective_client", "occurred_at"],
                name="acquisition_prospec_6c4da3_idx",
            ),
        ),
    ]
